# Generated by Django 4.1.3 on 2023-02-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_intrest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrest',
            name='intrest',
        ),
        migrations.AddField(
            model_name='intrest',
            name='intr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
