# Generated by Django 4.1.3 on 2023-02-08 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_followerscount_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrest',
            old_name='intr',
            new_name='intrest_name',
        ),
        migrations.CreateModel(
            name='intrest_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followig_user', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='intr', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='network.intrest')),
            ],
        ),
    ]
