# Generated by Django 4.1.5 on 2023-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_intr_intrest_intrest_name_intrest_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
