# Generated by Django 4.1.5 on 2023-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_delete_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrest_followers',
            old_name='followig_user',
            new_name='following_user',
        ),
    ]
